stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - website
  script:
    - nix build
  only:
    - dev

deploy:
  stage: deploy
  tags:
    - website
  script:
    - nix build
    - rsync -avz --checksum --delete ./result/ website@10.1.183.197:/home/website/content
  only:
    - main
