stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - nix
  script:
    - nix-build
  only:
    - dev

deploy:
  stage: deploy
  tags:
    - nix
  script:
    - nix-build
    - rsync -avz --delete ./result/ stdout@pwychowaniec.com:/home/stdout/stdout/
  only:
    - master
