stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - website
  script:
    - nix build

deploy:
  stage: deploy
  tags:
    - website
  script:
    - git rev-parse --short HEAD > src/meta.rev
    - nix build
    - rsync -avz --checksum --delete ./result/ website@10.1.183.197:/home/website/main
  only:
    - main

deploy-beta:
  stage: deploy
  tags:
    - website
  script:
    - echo "beta--$(git rev-parse --short HEAD)" > src/meta.rev
    - nix build
    - rsync -avz --checksum --delete ./result/ "website@10.1.183.197:/home/website/beta-${CI_COMMIT_BRANCH//\//-}"
  when: manual

remove-beta:
  stage: deploy
  tags:
    - website
  script:
    - ssh website@10.1.183.197 "chmod -R 755 /home/website/beta-${CI_COMMIT_BRANCH//\//-}"
    - ssh website@10.1.183.197 "rm -rf /home/website/beta-${CI_COMMIT_BRANCH//\//-}"
  when: manual
