stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - nix
  script:
    - nix-build
    - mkdir out
    - rsync -a result/ out/
    - chmod 777 -R out
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 14 days
    paths:
      - out

deploy:
  stage: deploy
  tags:
    - nix
  script:
    - rsync -avz --delete ./out/ stdout@pwychowaniec.com:/home/stdout/stdout/
  only:
    - master
