name = "mmai"
license = "MIT"
description = ""
homepage = "https://stdout.pwychowaniec.com"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Patryk Wychowaniec"
  homepage = "https://stdout.pwychowaniec.com"
