[package]
name = "stdout_server"
version = "0.1.0"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"