baseURL = "https://stdout.pwychowaniec.com"
title = "pwychowaniec"
languageCode = "en"
theme = "mmai"

[taxonomies]
    tag = "tags"
#    serie = "series" @todo

[params]
    dateFormat = "January 2, 2006"
